### ISSUE TITLE
postProcessHTMLLogs.sh fails for wala/portal-example-simple.html

### ISSUE THREAD

**Issue by mtorp** [cs-au-dk/jalangilogger#3]
The following execution of postProcessHTMLLogs results in an IndexOutOfBoundsException. It works  for other test cases

Node-version: v4.4.5
```
./scripts/instrumentHTMLFiles.sh
./scripts/startServer.sh
```
Open browser. Interact with application. Click p

```
./scripts/postProcessHTMLLogs.sh
```

results in 
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at dk.au.cs.casa.jer.TransformHtmlLogFiles.transformSourceLocation(TransformHtmlLogFiles.java
:149)
        at dk.au.cs.casa.jer.TransformHtmlLogFiles.iterateThroughJSONObjectAndChangeSL(TransformHtmlL
ogFiles.java:122)
        at dk.au.cs.casa.jer.TransformHtmlLogFiles.transformFile(TransformHtmlLogFiles.java:96)
        at dk.au.cs.casa.jer.TransformHtmlLogFiles.loopThroughAllFilesAndTransformThem(TransformHtmlL
ogFiles.java:45)
        at dk.au.cs.casa.jer.TransformHtmlLogFiles.loopThroughAllFilesAndTransformThem(TransformHtmlL
ogFiles.java:51)
        at dk.au.cs.casa.jer.TransformHtmlLogFiles.main(TransformHtmlLogFiles.java:29)
```

**Comment by barslev** [comment]
Fixed by commit fba84c1
